# Generated by Django 3.2.6 on 2021-08-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunr', '0003_auto_20210814_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
